// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmqvueetpfxzyofuqabp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtcXZ1ZWV0cGZ4enlvZnVxYWJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTQzMzgsImV4cCI6MjA3MTI5MDMzOH0.KqyqGaVLOAP6sjyPlXRJm0zlXEFVU9YnrcOwwUb_mx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});